git:
  userName: 123123
  password: 123123
  local:
    base:
      dir: /home/code-diff/git
svn:
  userName: 123123
  password: 123123
  local:
    base:
      dir: /home/code-diff/svn
svnjira:
  daysago: 365

server:
  port: 8085
  servlet:
    session:
      timeout: 3600
